// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1_nCvbEWldJolua_U5XU-dWcyRZ0yEc',
    appId: '1:737481588269:web:d9227fb8bb6672ed7a82a4',
    messagingSenderId: '737481588269',
    projectId: 'e-commerceapp-28',
    authDomain: 'e-commerceapp-28.firebaseapp.com',
    storageBucket: 'e-commerceapp-28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsyDu-wmjiso0PRexRjkd19evmPh_FIRc',
    appId: '1:737481588269:android:39e23b7364ac5f547a82a4',
    messagingSenderId: '737481588269',
    projectId: 'e-commerceapp-28',
    storageBucket: 'e-commerceapp-28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt12rBFOHXgs22OQD2jQ616Eez3vCnrDI',
    appId: '1:737481588269:ios:2f2a4786fadd2f1c7a82a4',
    messagingSenderId: '737481588269',
    projectId: 'e-commerceapp-28',
    storageBucket: 'e-commerceapp-28.appspot.com',
    androidClientId: '737481588269-m57ps83ak3sgn0rb5f4gb8ng39d1eu76.apps.googleusercontent.com',
    iosClientId: '737481588269-7gejnt0pvvpjba4cpvv0bt1iq1jqlpu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceWithBackend',
  );
}
